os: linux
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-xenial-7
    packages:
    - g++-5
    - clang-7
    - valgrind
    - xorg-dev
    - libcppunit-dev
    - cmake
before_script: mkdir build && cd build && if [ "${CXX}" = "clang++" ]; then export CXX=/usr/bin/clang++-7; fi && if [ "${CXX}" = "g++" ]; then export CXX=/usr/bin/g++-5; fi
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUTIL_BUILD_EXAMPLES=ON -DUTIL_BUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic" .. && make && ctest --verbose -D ExperimentalTest
